<!-- Generated by AI assistant: concise, actionable guidance for code agents -->
# Copilot / Agent Instructions for PS-RedFish-Client

Purpose
- Help AI coding agents become productive quickly in this repository by describing the current layout, how to discover code, and concrete commands to run locally.

Repository snapshot
- This repository currently contains the project README and license. See the project description: [README.md](README.md#L1-L3).

Quick discovery steps (first actions)
- List tracked source files and show file extensions used:

```bash
git ls-files | sed -n '1,200p'
# or, to find likely PowerShell code and modules:
git ls-files | rg --iglob '!node_modules' -n --hidden "\.(ps1|psm1|psd1|psm1)$" || true
```

- If `rg`/`ripgrep` is unavailable, fallback to `grep`:

```bash
git ls-files | grep -E "\.(ps1|psm1|psd1|psm1)$" || true
```

What agents should look for first
- Entry points: top-level PowerShell scripts (`*.ps1`), module files (`*.psm1`, `*.psd1`) and any `src/`, `modules/`, or `lib/` directories.
- Tests: search for `tests/`, `*-Tests.ps1`, or files under `spec/`.
- CI/build: look for GitHub Actions in `.github/workflows/` or shell/make scripts named `Makefile`, `build.sh`, `ci/*`.

Project-specific patterns and conventions
- Project name suggests a PowerShell Redfish client. Prioritize PowerShell file patterns and REST/HTTP helper modules when searching for network logic.
- Expect exported functions to live in `*.psm1` modules, with manifests in `*.psd1` if present.

Common tasks and concrete commands
- Run a repo-wide language search for quick orientation:

```bash
git ls-files | rg --hidden -n "\.ps1$|\.psm1$|\.psd1$|\.json$|\.yaml$|\.yml$" || true
```

- Run tests (if found): prefer a repository-provided test runner; otherwise run PowerShell Pester tests:

```bash
# from macOS / Linux with pwsh installed
pwsh -Command 'Invoke-Pester -Path tests -Output Detailed' || true
```

How to update this file (merging guidance)
- If a `.github/copilot-instructions.md` already exists in the future, merge by preserving any project-specific commands and CI notes. Keep this file focused on discoverable facts (files, build/test commands) rather than aspirational style guides.

Examples from this repo
- Project description available in [README.md](README.md#L1-L3) — start there to confirm intent and supported platforms.

When unsure, prefer safe, non-destructive actions
- Use read-only discovery commands first (`git ls-files`, `rg`, `sed`, `pwsh -Command Get-ChildItem`), and open files for context before making edits.

Feedback
- After running the discovery commands above, update this file with the exact entry points, test commands, and CI paths you find so agents can act directly.
